### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by Ar37-rs**
- Updated clipboard-win to 4.x,x
- Updated x11-clipboard to 0.6.x
- Change the minimum rust version to 1.59.0

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
> Change the minimum rust version to 1.59.0
> No breaking change

But that is a breaking change.

Also is there any benefit to these updates other than breaking MSRV?

**Comment by Ar37-rs** [comment]
@chrisduerr  oops sorry, it's  x11-clipboard 0.6.0 which depends on xcb 1.1+ as mentioned above requires rustc version 1.59.0+

**Comment by chrisduerr** [comment]
> @chrisduerr x11-clipboard 0.6.0 uses [T; N]::as_slice which requires rustc version 1.59.0+, otherwise won't compile

First of all, the documentation itself says 1.57.0 so I doubt this is what requires 1.59.0+. And it isn't really relevant *what* requires a newer Rust version but rather *why* it does. Unless it manages to provide actual benefits, updating to a new dependency that just puts further restrictions isn't really much of an upgrade.

**Comment by Ar37-rs** [comment]
@chrisduerr for now copypasta v0.7.1 is enough for desktop usage. this PR for the next version maybe, for future use case.

**Comment by chrisduerr** [comment]
You still haven't told me the actual motivation and benefits of updating these dependencies. Did you just bump the versions because it's easy without even checking what changed?

**Comment by Ar37-rs** [comment]
@chrisduerr never mind, because personally i use copypasta from my fork for one of my linux desktop-app projects which uses latest xcb version 1.1 directly

**Pull request closed without merging**
