### PR TITLE
Add Send + Sync + 'static bounds to dyn Error

### LINKED ISSUE #17: Add Send + Sync + 'static bounds to the Error type
Add `Send + Sync + 'static` bounds to the error type, i. e. change `dyn Error` to `dyn Error + Send + Sync + 'static`. 

In addition to being able to modify the clipboard and handle the error in a different thread, this change would enable interoperability with `anyhow`, `failure` and other error handling libraries. 

`x11_clipboard`'s Error type has these bounds (I have tried adding it to `rust-clipboard`), but I'm not sure about macos / windows / wayland. I'm happy to research it and create a PR to test all the platforms if CI tests all environments? I only have access to Linux.

### PR DESCRIPTION
**Pull request by mcobzarenco**
Add `Send + Sync + 'static` bounds to the error type, i. e. change `dyn Error` to `dyn Error + Send + Sync + 'static`.

~~It also adds a basic test.~~

Fixes #17

### CODE REVIEW

**Comment by mcobzarenco** [comment]
> It also adds a basic test.

Actually, this fails in travis for X11 on Linux -- I'll try to add [xvfb](https://docs.travis-ci.com/user/gui-and-headless-browsers/) to fix it.

**Comment by kchibisov** [comment]
Use NopClipboard if the goal is to only test that we don't break thread safety, etc.

**Comment by mcobzarenco** [comment]
I guess the goal was to ensure a set/get roundtrip works on all platforms -- adding `xvfb` fixed it for x11.

**Comment by kchibisov** [comment]
You're not testing Wayland, so I'm not sure what are you trying to achieve here tbqh with such test. I'd rather remove it since it's not making much sense.

**Comment by mcobzarenco** [comment]
> You're not testing Wayland,

Oh, fair enough. I just realized now that even if with features`x11` disabled and `wayland` enabled, `ClipboardContext` in `lib.rs` is not defined as `wayland_clipboard::ClipboardContext`. 

I am testing `ClipboardContext` for the current platform, so it tests everything else apart from Wayland (e.g. osx, windows and x11 on linux). 

> I'm not sure what are you trying to achieve here tbqh with such test. I'd rather remove it since it's not making much sense.

I can remove it, but don't you think there's value in having some tests? Even without testing Wayland, it still goes from no tests to testing osx, windows and x11 on linux :man_shrugging: 

> I can't even run those tests, since I don't have X11 installed on my system.

Isn't this just a general problem with having tests for any cross-platform library -- i.e. I assume you can't test the windows implementation either? I rely on CI for platforms I don't have around.

It should be easy to add an explicit Wayland test too -- though you'd have to configure travis to install it? Also, on a different note (and without knowing much about Wayland), the `wayland_clipboard::ClipboardContext::new` function takes `*mut c_void`. I guess that's why you removed the `new()` method from the `ClibboardProvider` trait that exists in `rust_clipboard` -- is it not possible to have a constructor with no arguments?

**Comment by mcobzarenco** [comment]
@kchibisov Btw, happy to change it whichever way you prefer, those are just thoughts -- please let me know

**Comment by mcobzarenco** [comment]
>No matter how you look at it, the correctness of this PR should be ensured by Rust's typesystem

Absolutely, the intent of adding a test was not to test the new `Error` bounds. Fair enough re: adding tests in a separate PR -- I removed the commit now

**Comment by kchibisov** [comment]
I'll also note, that tests should be done in upstream crates, not in a wrapper around those crates. If the goal is to test generic wrapper, you can test it over that generic impl.

**Comment by mcobzarenco** [comment]
Agreed that any kind of tests not specific to the wrapper should be done in upstream crates. However, the test I added pretty much just checks things are forwarded correctly as you say -- e.g. if I set and get a string I get back the same thing on all platforms.

**Comment by mcobzarenco** [comment]
Just a follow up to make sure you noticed my comment re:

> Fair enough re: adding tests in a separate PR -- I removed the commit now

No rush, just didn't want it to get lost in the discussion about testing

**Pull request merged**
