### PR TITLE
Add tests for ClipboardContext and NopClipboardContext

### PR DESCRIPTION
**Pull request by yykamei**
copypasta doesn't seem to have unit tests, so I accidentally made changes with the PR: https://github.com/alacritty/copypasta/pull/57

I want to make sure any changes are checked by running test codes. That's why I want to add test codes.

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
There are no tests for the exact reason the CI is failing this build.

These tests also would not have helped with the issue you mentioned at all.

**Comment by yykamei** [comment]
OK, I understood this PR doesn't help the issue I mentioned. What should I do to avoid the issue?

**Comment by kchibisov** [comment]
I mean, you could test for object safety, obviously, which is a completely different test and it doesn't require anything special.

It seems like you haven't understood what the exact reason was why I reverted the change. Basically `rust` can't have `Box<dyn Trait>` trait objects where `Trait` has a generic on any of its methods, so that's why your case doesn't work. What you should do instead is to basically build the clipboard and put it into the `Box<dyn ClipboardProvider>`, no need to actually `set_contents`, etc. 

Just testing with `Nop` clipboard on its own should be more than enough. though or with doc tests. Actual building won't work.

**Comment by yykamei** [comment]
Thank you for your explanation.

**Pull request closed without merging**
